dictionaries = [
    "en_us",
    "en_gb",
    "de",
    "es",
    "ru",
]
words = [
    "ablablalbal",
    "abrt",
    "abuf",
    "ackacq",
    "aclk",
    "acqsig",
    "adap",
    "adaptee",
    "adaptee's",
    "addrw",
    "adist",
    "aerq",
    "airblade",
    "allow",
    "alsa",
    "ambv",
    "amine",
    "andrewstuart",
    "aoff",
    "aphighpass",
    "aplowpass",
    "aplus",
    "apvts",
    "arcticicestudio",
    "argjson",
    "asciicast",
    "asmsyntax",
    "asyncrun",
    "atcursor",
    "atkm",
    "atmel",
    "atol",
    "atom",
    "augroup",
    "author",
    "auto",
    "autocmd",
    "autocmds",
    "autocommands",
    "autosort",
    "autosource",
    "avg",
    "bashls",
    "bbappend",
    "bclean",
    "bfrg",
    "bidi",
    "bigfish",
    "binfo",
    "biquad",
    "bitbake",
    "bklight",
    "blitter",
    "blocking",
    "bname",
    "bofs",
    "boid",
    "boids",
    "borderchars",
    "box",
    "breakpoint",
    "btns",
    "bufclean",
    "bufhidden",
    "buflisted",
    "bufnr",
    "buftype",
    "bufwinid",
    "bufwritepost",
    "busid",
    "button",
    "bysecond",
    "byteidx",
    "cache",
    "caiaq",
    "calib",
    "call",
    "callhier",
    "carxp",
    "cbfunc",
    "cbuf",
    "cclose",
    "ccol",
    "cdat",
    "cdelledonne",
    "cdev",
    "cdjs",
    "cest",
    "cexpr",
    "charidx",
    "charlespascoe",
    "charp",
    "chrisbra",
    "christianchiarulli",
    "chrony",
    "chrony's",
    "chronyc",
    "chronyd",
    "clangd",
    "classobj",
    "claussen",
    "claußen",
    "clbin",
    "client",
    "clientd",
    "clientid",
    "clin",
    "cmake",
    "cmakelint",
    "cmakerc",
    "cmdline",
    "cmocka",
    "cnext",
    "coap",
    "coc",
    "cocrc",
    "code",
    "codehilite",
    "coeffs",
    "coefs",
    "cohama",
    "colnr",
    "colorschemes",
    "commp",
    "completionmatcher",
    "cond",
    "config",
    "configurability",
    "contactid",
    "containedin",
    "conv",
    "coso",
    "cpld",
    "cppcoreguidelines",
    "cpptools",
    "cpputest",
    "cppx",
    "cprevious",
    "craggs",
    "creational",
    "cris",
    "croql",
    "csample",
    "csamplestopcmbuffer",
    "csidl",
    "cspell",
    "ctags",
    "cterm",
    "ctermbg",
    "ctermcolor",
    "ctermfg",
    "ctermfgs",
    "cterms",
    "ctermul",
    "cto",
    "ctt",
    "cuda",
    "curbuf",
    "curcol",
    "curdir",
    "curline",
    "current",
    "cursorline",
    "curtine",
    "customisation",
    "cword",
    "cxlmd",
    "cxlr",
    "cxlrd",
    "cxlsd",
    "cxx",
    "cygwin",
    "cyttsp",
    "d'th",
    "darkorange",
    "darkorchid",
    "data",
    "dattr",
    "dcmake",
    "dconnections",
    "ddi",
    "deassert",
    "debugfs",
    "debugpy",
    "defconfig",
    "delayline",
    "deletebufline",
    "demucs",
    "dev",
    "devfs",
    "devicetree",
    "devm",
    "devt",
    "devtmpfs",
    "diacr",
    "diffoff",
    "diffthis",
    "dimm",
    "dimms",
    "disable",
    "displink",
    "dmac",
    "doautocmd",
    "dockercompose",
    "docset",
    "documenation",
    "dogerc",
    "dtls",
    "dtrans",
    "dwaxidmac",
    "echoerr",
    "echoh",
    "echohl",
    "echom",
    "echon",
    "echow",
    "edev",
    "edid",
    "eeprom",
    "eeproms",
    "efm",
    "elif",
    "ema",
    "emaf",
    "email",
    "emdev",
    "emsg",
    "enddef",
    "endfor",
    "endfun",
    "endfunc",
    "endfunction",
    "endwhile",
    "enforce",
    "enotsupp",
    "env",
    "ericcurtin",
    "err",
    "esc",
    "evbit",
    "ewma",
    "exercism's",
    "exrc",
    "f",
    "fatih",
    "feedkeys",
    "feff",
    "fernrc",
    "fftw",
    "fgconsole",
    "filebpm",
    "filereadable",
    "filp",
    "filt",
    "filtype",
    "firstline",
    "flag",
    "flast",
    "fmat",
    "fmtopts",
    "fname",
    "fnameescape",
    "fnamemodify",
    "foldlevel",
    "foldlevelstart",
    "foldmethod",
    "foldnestmax",
    "fontx",
    "formatexpr",
    "fpack",
    "frms",
    "frsig",
    "ftape",
    "ftrace",
    "ftype",
    "ftypes",
    "fugitiveblame",
    "fugitiverc",
    "funcobj",
    "function",
    "fwnode",
    "fzf",
    "gclog",
    "gdiff",
    "gedit",
    "gepolter",
    "gergap",
    "getbufinfo",
    "getbufline",
    "getbufvar",
    "getcwd",
    "gethifontmask",
    "getline",
    "getpos",
    "getreg",
    "getrommel",
    "gfp",
    "gfpflags",
    "ggrep",
    "ginko",
    "gio",
    "gitcommit",
    "gitgutter",
    "gitgutterrc",
    "gles",
    "glfsr",
    "glog",
    "glue",
    "gmove",
    "godlygeek",
    "golay",
    "gopls",
    "gosukiwi",
    "gotoid",
    "gpio",
    "gpiod",
    "gpiof",
    "gpiolib",
    "gpiomod",
    "gpios",
    "gread",
    "gregkh",
    "grepprg",
    "greview",
    "gruvbox",
    "guibg",
    "guicolor",
    "guifg",
    "guifgs",
    "guisp",
    "gwrite",
    "habamax",
    "handle",
    "hantro",
    "hardknott",
    "hartman",
    "haswts",
    "hblank",
    "hclk",
    "hdata",
    "hdcp",
    "hdisp",
    "heorhiy",
    "hier",
    "hlist",
    "hllen",
    "hlsearch",
    "hlset",
    "holthuis",
    "honza",
    "hotcue",
    "hpulse",
    "hrsh",
    "hsts",
    "hvsync",
    "hwclock",
    "hweight",
    "hwparam",
    "hwrap",
    "hyst",
    "i",
    "iamcco",
    "icase",
    "ifdef",
    "implementational",
    "impls",
    "improveme",
    "includet",
    "incsearch",
    "indexof",
    "infiniteloop",
    "ingo",
    "inoremap",
    "inprogress",
    "input",
    "int",
    "integ",
    "interruptible",
    "intvh",
    "invokable",
    "io",
    "ioc",
    "ioctl",
    "ioctl's",
    "iomem",
    "iommus",
    "ioremap",
    "ioresource",
    "irqctx",
    "irqf",
    "irqrestore",
    "irqs",
    "irqsave",
    "irugo",
    "is",
    "iskeyword",
    "iunmap",
    "jalali",
    "jasonccox",
    "jassert",
    "javajre",
    "jclsn",
    "jetls",
    "jgade",
    "jmap",
    "jmax",
    "jnurmine",
    "jochen",
    "jpalardy",
    "juce",
    "jumpable",
    "junegunn",
    "kabb",
    "kahlert",
    "kallsyms",
    "kalman",
    "kasan",
    "kbdiacr",
    "kbdiacrs",
    "kbdiacrsuc",
    "kbdiacruc",
    "kbentry",
    "kbit",
    "kbkeycode",
    "kbleds",
    "kbledstatus",
    "kbsentry",
    "kbuild",
    "kcompactd",
    "kcsan",
    "kdaddio",
    "kddelio",
    "kddisabio",
    "kdenabio",
    "kdfontop",
    "kdgetkeycode",
    "kdgetled",
    "kdgetmode",
    "kdgkbdiacr",
    "kdgkbdiacruc",
    "kdgkbent",
    "kdgkbled",
    "kdgkbmeta",
    "kdgkbmode",
    "kdgkbsent",
    "kdgkbtype",
    "kdkbdrep",
    "kdmapdisp",
    "kdmktone",
    "kdsetled",
    "kdsigaccept",
    "kdskbdiacr",
    "kdskbdiacruc",
    "kdskbent",
    "kdskbled",
    "kdskbmeta",
    "kdskbmode",
    "kdskbsent",
    "kdunmapdisp",
    "keywordprg",
    "kfifo",
    "kfree",
    "kgid",
    "khugepaged",
    "kiocsound",
    "kkoomen",
    "kmalloc",
    "kmap",
    "kmemcg",
    "kmeta",
    "kobj",
    "kontrol",
    "kora",
    "kprobe",
    "kprobes",
    "kref",
    "kswapd",
    "ksys",
    "kubernetes",
    "kuid",
    "kworker",
    "kzalloc",
    "lafreniere",
    "lafrenière",
    "lambdalisue",
    "lastline",
    "lastlnum",
    "lauter",
    "ldev",
    "ldisc",
    "le",
    "ledctl",
    "leds",
    "left",
    "lerp",
    "lervag",
    "lexima",
    "leximarc",
    "lfsr",
    "lfsrs",
    "libgpiod",
    "libqsqlmysql",
    "libxwax",
    "lightcyan",
    "lightmagenta",
    "lightred",
    "lightyellow",
    "lindgren",
    "linehl",
    "linenr",
    "lines",
    "linke",
    "linksto",
    "listchars",
    "lldb",
    "llseek",
    "lnflt",
    "lnum",
    "loadview",
    "localleader",
    "lock",
    "loff",
    "logid",
    "longkind",
    "lowpass",
    "lros",
    "lrus",
    "ls",
    "lserver",
    "lshifted",
    "lspgfm",
    "lspserver",
    "lspservers",
    "lspsrv",
    "lspsrvlst",
    "lucene",
    "lum",
    "luochen",
    "luts",
    "lvds",
    "makefiles",
    "makeprg",
    "makie",
    "mapleader",
    "maplocalleader",
    "markdownlint",
    "markonm",
    "martinlroth",
    "matchlist",
    "mathfunctions",
    "max",
    "maxlinenr",
    "maxnr",
    "mbus",
    "mcount",
    "mdelay",
    "mdev",
    "mhinz",
    "migraphx",
    "milankovic",
    "mileszs",
    "millis",
    "minheight",
    "mixvibesdvs",
    "mixxx",
    "mixxx's",
    "mkview",
    "mmflags",
    "mmzone",
    "morhetz",
    "mptr",
    "mqtt",
    "mydev",
    "mydriver",
    "myfactor",
    "mygroup",
    "myid",
    "myint",
    "myintarray",
    "myjob",
    "mylong",
    "mylène",
    "mymodule",
    "mystr",
    "mytask",
    "myvimdir",
    "myvimrc",
    "n'th",
    "nargs",
    "nasm",
    "ndarray",
    "neoclide",
    "neocmakelsp",
    "nerdfont",
    "nerdtree",
    "networkd",
    "newev",
    "nicedisp",
    "nicehd",
    "nlines",
    "nmap",
    "nmea",
    "nnoremap",
    "no",
    "noarg",
    "noautochdir",
    "nobackup",
    "nocfi",
    "nocompatible",
    "nocursorbind",
    "nocursorline",
    "noerrorbells",
    "noexpandtab",
    "nofile",
    "nofs",
    "nohlsearch",
    "noidle",
    "nolist",
    "nomodifiable",
    "nomodified",
    "nonu",
    "nop",
    "nopos",
    "noretry",
    "nornu",
    "noruler",
    "noscrollbind",
    "noshowcmd",
    "noshowmode",
    "noswapfile",
    "notexists",
    "notif",
    "novisualbell",
    "nowait",
    "nowritebackup",
    "npcm",
    "nplot",
    "nproc",
    "npx",
    "nrshift",
    "nsamples",
    "nslots",
    "ntpeters",
    "nullptr",
    "numa",
    "numtaps",
    "nuxt",
    "nvcode",
    "nvdimm",
    "nvim",
    "nvmem",
    "nwrites",
    "objc",
    "octol",
    "old",
    "oldev",
    "ollama",
    "omap",
    "omni",
    "omnicompl",
    "omnifunc",
    "oneline",
    "openembedded",
    "openqry",
    "oper",
    "optimised",
    "otool",
    "out",
    "outro",
    "overtemp",
    "owilliams",
    "packageconfig",
    "packagegroup",
    "packagegroups",
    "pad",
    "pairtools",
    "pandoc",
    "parens",
    "pargs",
    "partno",
    "pboettch",
    "pcdrv",
    "pceraser",
    "pcexpander",
    "pdata",
    "pdc",
    "pdev",
    "pdu",
    "pdus",
    "pengutronix",
    "perlnavigator",
    "pgid",
    "phandle",
    "phong",
    "pilia",
    "pimpl",
    "pineapplegiant",
    "pio",
    "pioneera",
    "pioneerb",
    "pkgbuild",
    "pkl",
    "plaintex",
    "player",
    "pluginlist",
    "pmenu",
    "poison",
    "popcountll",
    "popid",
    "potmeter",
    "powerline",
    "ppos",
    "pragprog",
    "pregain",
    "preservim",
    "primary",
    "printf",
    "printk",
    "probe",
    "projekte",
    "projucer",
    "pseewald",
    "psliwka",
    "ptag",
    "ptjump",
    "ptmux",
    "ptpc",
    "pttw",
    "puid",
    "pulkomandy",
    "pullup",
    "pum",
    "pumvisible",
    "puper",
    "puremourning",
    "pyright",
    "pyxversion",
    "qegl",
    "qglx",
    "qhxy",
    "qlcd",
    "qmysql",
    "qnx",
    "qsgd",
    "quintptr",
    "quitall",
    "qvxy",
    "qwgl",
    "rafamadriz",
    "rainbowrc",
    "ralink",
    "rbaeuf",
    "rbsh",
    "rcrb",
    "rcuref",
    "rdrol",
    "recascading",
    "reclaim",
    "record",
    "recue",
    "reflectee",
    "reg",
    "rekord",
    "relativenumber",
    "remove",
    "replaygain",
    "rereport",
    "resettet",
    "resizex",
    "response",
    "retab",
    "retarget",
    "reverseroll",
    "rgba",
    "rhpf",
    "rhysd",
    "riaa",
    "right",
    "rigkontrol",
    "ringbuffer",
    "royalblue",
    "rrcosfilter",
    "rryan",
    "rshfited",
    "rtcautotrim",
    "rtcsync",
    "rtp",
    "runtimepath",
    "rustanalyzer",
    "rwsem",
    "rxfifo",
    "ryanoasis",
    "samplefile",
    "savgol",
    "savitzky",
    "scalar",
    "scrnmap",
    "scrolloff",
    "sctp",
    "scxml",
    "seagreen",
    "secondary",
    "sendexpr",
    "serato",
    "seratocd",
    "seratocv",
    "seratos",
    "serialised",
    "serialiser",
    "serid",
    "setbufvar",
    "setf",
    "setl",
    "setline",
    "setlocal",
    "setoptions",
    "sheerun",
    "shellcheck",
    "shellescape",
    "shfmt",
    "shortmessage",
    "shumphrey",
    "sidea",
    "sideb",
    "sigidx",
    "signcolumn",
    "simple",
    "skip",
    "skipnl",
    "slimerc",
    "slope",
    "smap",
    "smartmontools",
    "smbus",
    "sndrv",
    "snmp",
    "sonariac",
    "sonarjs",
    "sonarlint",
    "spaceduck",
    "spin",
    "spinup",
    "splitbelow",
    "spontane",
    "sprunge",
    "sq",
    "srcu",
    "ssd",
    "ssds",
    "sstate",
    "startify",
    "startinsert",
    "startwin",
    "statusline",
    "stopinsert",
    "strdisplaywidth",
    "strftime",
    "stridx",
    "stringizer",
    "strntoll",
    "struct",
    "structuredtext",
    "strutf",
    "subchain",
    "subcomponent",
    "subconfig",
    "superhtml",
    "svideo",
    "swnode",
    "synchronise",
    "synstack",
    "sysclock",
    "sysex",
    "sysfs",
    "sysimage",
    "systemwide",
    "szw",
    "tabchars",
    "tabe",
    "tabline",
    "tabsz",
    "tabularize",
    "tagfunc",
    "taketheirs",
    "taskbars",
    "tccmp",
    "tcpos",
    "technik",
    "termbin",
    "termencoding",
    "termguicolors",
    "termwinscroll",
    "test",
    "texlab",
    "texthl",
    "tfree",
    "th",
    "themeconfig",
    "thumshirn",
    "timecode",
    "timecoder",
    "timecodes",
    "timedatectl",
    "timedated",
    "timeoutlen",
    "timesync",
    "timesyncd",
    "tjump",
    "tmode",
    "tmpl",
    "tmux",
    "tnoremap",
    "todos",
    "tolower",
    "tomasiser",
    "tombi",
    "toolset",
    "topline",
    "touchscreen",
    "tpope",
    "traktor",
    "traktoraudio",
    "traktorkontrols",
    "traktorkontrolx",
    "traktorscratchmk",
    "traktorscratchsidea",
    "traktorscratchsideb",
    "trigidx",
    "trimrtc",
    "trunc",
    "ttimeoutlen",
    "ttyp",
    "tweraser",
    "twexpander",
    "typehier",
    "typeof",
    "uapi",
    "uevent",
    "uevents",
    "ufacd",
    "ultisnips",
    "ultisnipsrc",
    "umode",
    "unblank",
    "undercurl",
    "undertemp",
    "undodir",
    "undofile",
    "unformat",
    "uniquify",
    "uniscrnmap",
    "unlock",
    "unqual",
    "unshallow",
    "unsmoothed",
    "uparrow",
    "updatetime",
    "urlhandler",
    "use",
    "useb",
    "userspace",
    "v",
    "vaio",
    "validate",
    "vargs",
    "vblank",
    "vboxuser",
    "vbprintk",
    "vc",
    "vcmode",
    "vcol",
    "vddio",
    "vdisp",
    "vepu",
    "viewoptions",
    "vimhome",
    "vimls",
    "vimlsp",
    "vimqt",
    "vimrc",
    "vimscript",
    "vimspector",
    "vimspectorrc",
    "vimtex",
    "vimtexrc",
    "vint",
    "vinylla",
    "vinylsideb",
    "vlin",
    "vman",
    "vmap",
    "vmax",
    "vmbus",
    "vmlinux",
    "vnoremap",
    "voff",
    "voldikss",
    "vpitch",
    "vprintk",
    "vpulse",
    "vscode",
    "vsnip",
    "vsplit",
    "vt",
    "vt's",
    "waitv",
    "wcfg",
    "wclazy",
    "weeknum",
    "westeri",
    "wgwoods",
    "widgethelper",
    "wildmenu",
    "wildmode",
    "wildoptions",
    "winbufnr",
    "wincmd",
    "windo",
    "winids",
    "winnr",
    "write",
    "xdg",
    "xgridcolor",
    "xlabel",
    "xlabelcolor",
    "xmap",
    "xnoremap",
    "xored",
    "xors",
    "xoshiro",
    "xournal",
    "xsel",
    "xwax",
    "ycm",
    "ycmrc",
    "yegappan",
    "yggdroot",
    "ygridcolor",
    "ylabel",
    "ylabelcolor",
    "yocto",
    "yuezk",
    "zeavim",
    "zeavimrc",
    "zeekay",
    "zyedidia",
    "zyiw",
    "Ꞩ",
]
